### PR TITLE
fix multiple decimal points in a number string

### LINKED ISSUE #8: Returns NaNs for certain inputs
Hi, thanks for your work on this library

I noticed that reversing this particular path produces bad output:
```
> require('svg-path-reverse').reverse('M20.888 43.504c.027.07.074.119.139.144.067.028.131.037.191.026.07-.014.104-.041.104-.082V36.92c-.004-.024-.027-.062-.07-.114a.658.658 0 0 0-.173-.15c-.245-.153-.53-.185-.858-.098-.086.023-.17.051-.25.086a1.906 1.906 0 0 0-.546.364 1.923 1.923 0 0 0-.248.307c-.08.124-.15.261-.207.411a2.894 2.894 0 0 0-.14.53 4.011 4.011 0 0 0-.028 1.064c.018.133.037.256.06.37.022.112.057.234.103.367.048.133.09.245.127.338.036.093.09.206.16.339.072.132.13.238.17.315.044.076.108.183.194.32l.194.3.204.305c.155.233.271.41.349.53.078.12.169.276.274.467.107.193.19.37.25.533z')
'M NaN NaN C NaN NaN NaN NaN NaN NaN L NaN NaN C NaN NaN NaN NaN NaN NaN A 4.011 0 0 0 0 NaN NaN A 2.894 2.894 0 0 1 NaN NaN C NaN NaN NaN NaN NaN NaN A 1.923 0 0 0 0 NaN NaN A 1.906 1.906 0 0 1 NaN NaN C NaN NaN NaN 36.388000000000005 NaN 36.55800000000001 C NaN 36.471000000000004 NaN 36.50300000000001 NaN 36.656000000000006 A 0.658 0 0 0 0 NaN 36.806000000000004 C NaN 36.858000000000004 NaN 36.896 NaN 36.92 L NaN NaN C 20.847 43.422 20.915000000000003 43.489999999999995 20.888 43.504 Z'
```

I suspect could it be the `-` values? My other inputs up to this point have all worked great

### PR DESCRIPTION
**Pull request by Eschon**
Fixes #8 

I'm not 100% happy with the solution. I would prefer a solution without a loop but I didn't find one.

### CODE REVIEW

File: reverse.js [hunk 1]
```diff
@@ -20,12 +20,20 @@
...
     // preprocess "d" so that we have spaces between values
     d = d.replace(/,/g,' ')
          .replace(/([^eE])-/g,'$1 -')
          .replace(/\s*([achlmqstvzACHLMQSTVZ])\s*/g," $1 ")
          .replace(/\s+/g, ' ');
 
+    while (regexp.test(d)) {
+      d = d.replace(regexp, '$1 $2');
+    }
+
```
Comment (Pomax) [inline reverse.js]: no need for any ifs, we can just add this replacement as part of the four step replacement above. If the pattern matches, it'll replace as needed. If it doesn't, it's a noop.

File: reverse.js [hunk 2]
```diff
@@ -20,12 +20,20 @@
    * and/or shortcut commands.
    */
   function normalizePath(d) {
+    // regular expression for detecting and replacing multiple decimal points
+    // in a continuous string
+    var regexp = /(\d*\.\d+)((\.\d*)+)/g;
```
Comment (Pomax) [inline reverse.js]: note that scientific notation is legal, so we'll need an optional `(e-?\d+)?` before that second decimal point to catch things like `"m0 0 L 100 0 L 1.0e2.1e3 L 0 100 z"`

**Review by Pomax — CHANGES_REQUESTED** [review]

File: reverse.js (hunk 1 above)
Comment (Eschon) [reply reverse.js]: I tried to get it into the replacements above. Problem is it needs the loop. If we have something like `c.027.07.074.119.139.144` (taken from the example in #8) it would only replace the first occurrence producing  
`c.027 .07.074.119.139.144`

File: reverse.js (hunk 2 above)
Comment (Eschon) [reply reverse.js]: Good point, didn't think about that. I fixed it and added a test case.

File: reverse.js (hunk 1 above)
Comment (Pomax) [reply reverse.js]: You don't, because the replace function allows a regexp as first argument, [and a _function_ as second argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_the_replacement) for when you need more complex transforms:

```js
var d = "c.027.07.074.119.139.144c.027.07.074.119.139.144";
d = d.replace(/,/g, " ")
     .replace(/([^eE])-/g, "$1 -")
     .replace(/\s*([achlmqstvzACHLMQSTVZ])\s*/g, " $1 ")
     .replace(/\s+/g, " ")
     .replace(/(\d*\.\d+)((\.\d*)+)/g, (_, g1, g2) => g1 + g2.replaceAll(".", " ."));
```

yielding ` c .027 .07 .074 .119 .139 .144 c .027 .07 .074 .119 .139 .144`.

To explain that function, the first argument is the full pattern, which we don't care about, after that each argument is a capture group. Since we want to insert spaces in front of every decimal point in the second group, we just literally do that. No loops required.

File: test.js [hunk 3]
```diff
@@ -62,3 +62,16 @@ prenormalized = "M 0.1 0 L 10.1 10";
...
 if (prenormalized !== reverse(reverse(path))) fail("scientific notation, uppercase, negative exponent (round trip)");
+
+
+path = "M20 43c.027.07.074.119.139.144.067.028.131.037.191.026";
+prenormalized = "M 20 43 C 20.027 43.07 20.074 43.119 20.139 43.144 C 20.206 43.172 20.27 43.181 20.33 43.17";
+normalized = normalize(path);
+if (normalized !== prenormalized) fail(`multiple decimal points (normalize): ${normalized}`);
+if (prenormalized !== reverse(reverse(path))) fail('multiple decimal points (round trip)');
+
+path = "m0 0 L 100 0 L 1.0e2.1e3 L 0 100 z";
```
Comment (Pomax) [inline test.js]: this may need to become `m0 0 L 1000e-1.0 L 1.0e2.1e3 L 0 100 z` to make sure that a negative exponent scientific number also does what we expect it to do.

**Review by Pomax — CHANGES_REQUESTED** [review]

File: reverse.js (hunk 1 above)
Comment (Eschon) [reply reverse.js]: Oh, I didn't know about that. That's neat. I updated the code accordingly.

File: test.js (hunk 3 above)
Comment (Eschon) [reply test.js]: Good point, but I think the example you posted should already be covered by the test case for negative exponents.
I did a slightly different change to have multiple decimal points with a negative exponent.

File: reverse.js [hunk 4]
```diff
@@ -24,7 +24,8 @@
     d = d.replace(/,/g,' ')
          .replace(/([^eE])-/g,'$1 -')
          .replace(/\s*([achlmqstvzACHLMQSTVZ])\s*/g," $1 ")
-         .replace(/\s+/g, ' ');
+         .replace(/\s+/g, ' ')
+         .replace(/(\d*\.\d+([eE]-?\d+)?)((\.\d*)+)/g, (_, g1, g2, g3) => g1 + g3.replaceAll(".", " ."));
```
Comment (Pomax) [inline reverse.js]: One last thing here: `((\.\d*)+` should be `((\.\d+)+` so we don't try to turn patterns like `4.2..` into `4.2 . .`

**Review by Pomax — DISMISSED** [review]

File: reverse.js (hunk 4 above)
Comment (Eschon) [reply reverse.js]: Good point, I updated the regular expression

**Review by Pomax — APPROVED** [review]

**Comment by Pomax** [comment]
Nice, in it goes!

**Comment by Pomax** [comment]
v1.4.0 published to npm
